name: CI
on:
  push:
    branches:
    - master
    - development

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.0,name=iPhone 11 Pro']
        xcode: ['/Applications/Xcode_12.app/Contents/Developer']
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: 'true'
          lfs: 'true'
      - name: Bundle Install
        run: bundle install
      - name: Dependencies
        run: bundle exec pod install
        env:
          DEVELOPER_DIR: ${{ matrix.xcode }}
      - name: Build and test
        run: bundle exec fastlane scan --destination "${destination}" --scheme "MangaReader"
        env:
          destination: ${{ matrix.destination }}
          DEVELOPER_DIR: ${{ matrix.xcode }}
      - name: Releasing
        run: bundle exec fastlane beta
        env:
          DEVELOPER_DIR: ${{ matrix.xcode }}
